[theme]
#White Background
#base="light"
#primaryColor="#FF4B4B"
#backgroundColor="#FFFFFF"
#secondaryBackgroundColor="#F0F2F6"
#textColor="#31333F"

#Dark Background
primaryColor = "#d33682"
backgroundColor = "#002b36"
secondaryBackgroundColor = "##99d7e8"
textColor = "#fff"
font="sans serif"

[client]
showSidebarNavigation = false